-- MySQL Script generated by MySQL Workbench
-- Thu Aug 29 11:21:49 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema animals
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema animals
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `animals` DEFAULT CHARACTER SET utf8 ;
USE `animals` ;

-- -----------------------------------------------------
-- Table `animals`.`adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animals`.`adresse` (
  `idadresse` INT NOT NULL AUTO_INCREMENT,
  `adresse` VARCHAR(250) NULL,
  `code_postal` VARCHAR(6) NULL,
  `ville` VARCHAR(45) NULL,
  PRIMARY KEY (`idadresse`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animals`.`Proprios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animals`.`Proprios` (
  `idProprios` INT NOT NULL AUTO_INCREMENT,
  `nom_proprio` VARCHAR(45) NULL,
  `prenom_proprio` VARCHAR(45) NULL,
  `adresse_idadresse` INT NOT NULL,
  PRIMARY KEY (`idProprios`),
  INDEX `fk_Proprios_adresse1_idx` (`adresse_idadresse` ASC),
  CONSTRAINT `fk_Proprios_adresse1`
    FOREIGN KEY (`adresse_idadresse`)
    REFERENCES `animals`.`adresse` (`idadresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animals`.`race`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animals`.`race` (
  `idrace` INT NOT NULL AUTO_INCREMENT,
  `nom_race` VARCHAR(45) NULL,
  PRIMARY KEY (`idrace`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animals`.`Animals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animals`.`Animals` (
  `idAnimals` INT NOT NULL AUTO_INCREMENT,
  `nom_animal` VARCHAR(45) NULL,
  `date_naissance` DATETIME NULL,
  `Proprios_idProprios` INT NOT NULL,
  `race_idrace` INT NOT NULL,
  PRIMARY KEY (`idAnimals`),
  INDEX `fk_Animals_Proprios1_idx` (`Proprios_idProprios` ASC),
  INDEX `fk_Animals_race1_idx` (`race_idrace` ASC),
  CONSTRAINT `fk_Animals_Proprios1`
    FOREIGN KEY (`Proprios_idProprios`)
    REFERENCES `animals`.`Proprios` (`idProprios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Animals_race1`
    FOREIGN KEY (`race_idrace`)
    REFERENCES `animals`.`race` (`idrace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
